eureka:
  instance:
    # 注册服务IP，而不是服务器名称
    prefer-ip-address: true
  client:
    # 向eureka注册服务
    register-with-eureka: true
    # 拉取注册表的本地副本
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# TODO 该配置是spring security用于服务授权的配置，为了便于测试，将配置注释，若要权限服务支持，需要将该配置打开
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8901/user
##      token-info-uri: http://localhost:8901/oauth/check_token
#    client:
#      access-token-uri: http://localhost:8901/oauth/token
#      user-authorization-uri: http://localhost:8901/oauth/authorize
#      client-id: license
#      client-secret: license

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.110
          auto-create-topics: true
      bindings:
        # 该属性将input通道映射到orgChangeTopic的队列中
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: license-service
  redis:
    host: 192.168.1.110
    port: 6379
    password: wondertek

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.baifc: DEBUG




