eureka:
  instance:
    # 注册服务IP，而不是服务器名称
    prefer-ip-address: true
  client:
    # 向eureka注册服务
    register-with-eureka: true
    # 拉取注册表的本地副本
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user
#      token-info-uri: http://localhost:8901/oauth/check_token
    client:
      access-token-uri: http://localhost:8901/oauth/token
      user-authorization-uri: http://localhost:8901/oauth/authorize
      client-id: license
      client-secret: license

